<?php $this->headTitle($page->getTitle()); ?>
<?php $this->headMeta($page->getSummary(), 'description'); ?>
<?php $this->layout($page->getLayout()); ?>
<?php
$bc = $this->navigation('cms_tree');
$this->placeholder('bodyClass')->set('cmspage-' . $page->getId());
$bc->findOneBy('id', 'cmspage-' . $page->getId())->setActive(True);
echo $this->navigation('cms_tree')->breadcrumbs();
?>
<hgroup>
    <h1 style="margin: .25em 0 .1em 0;"><?php echo $this->escapeHtml($page->getTitle()); ?></h1>
    <?php if($subtitle = $page->getSubtitle()) : ?>
        <h2><?php echo $this->escapeHtml($subtitle); ?></h2>
    <?php endif; ?>
</hgroup>
<?php if($summary = $page->getSummary()) : ?>
    <p class="summary"><?php echo $this->escapeHtml($summary); ?></p>
<?php endif; ?>

<?php foreach($page->getContentRows() as $row) : ?>
    <?php if(!$row->hasContents()) : ?>
        <?php continue; ?>
    <?php endif; ?>

    <div class="row">
        <?php foreach($row->getContents() as $content) : ?>
            <?php if(!$content->getVisible()) : ?>
                <?php continue; ?>
            <?php endif; ?>
            <?php echo $this->contentRenderer($content); ?>
        <?php endforeach; ?>
    </div>
<?php endforeach; ?>

<?php $this->placeholder('demoSubnav')->captureStart(); ?>
    <section>
        <h3>Unterseiten (Demo)</h3>
        <div class="row">
            <div class="12u">
                <?php echo $this->navigation('cms_tree')
                    ->menu()
                    ->setOnlyActiveBranch(true)
                    ->setRenderParents(false) ?>
            </div>
        </div>
    </section>
<?php $this->placeholder('demoSubnav')->captureEnd(); ?>