<table class="table">
    <thead>
        <tr>
            <td>ID</td>
            <th>Titel</th>
            <th>Aktionen</th>
        </tr>
    </thead>
    <?php foreach($pages as $page) : ?>
        <?php $url = $this->url('zfcadmin/lwcpages', array(
            'action' => 'edit', 'id' => $page->getId()
        )); ?>
        <tr>
            <td><?php echo $page->getId();?></td>
            <td><?php echo $page->getTitle();?></td>
            <td><a href="<?php echo $url; ?>">Bearbeiten</a></td>
        </tr>
    <?php endforeach; ?>
</table>